# .pre-commit-config-simple.yaml - Simplified config that works around network issues
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Stable version
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ['-e', 'SC2034']

  - repo: local
    hooks:
      - id: python-black
        name: Black Python formatting
        entry: sh
        language: system
        types: [python]
        args:
          - -c
          - |
            if command -v black >/dev/null 2>&1; then
              black --check --diff "$@"
            else
              echo "Black not found, installing..."
              pip install black==23.12.1 && black --check --diff "$@"
            fi

      - id: python-flake8
        name: Flake8 Python linting
        entry: sh
        language: system
        types: [python]
        args:
          - -c
          - |
            if command -v flake8 >/dev/null 2>&1; then
              flake8 --max-line-length=88 --extend-ignore=E203,W503,F401,F541,E501 "$@"
            else
              echo "Flake8 not found, installing..."
              pip install flake8==6.1.0 && flake8 --max-line-length=88 --extend-ignore=E203,W503,F401,F541,E501 "$@"
            fi

      - id: trivy-fs
        name: Trivy filesystem scan
        entry: sh
        language: system
        pass_filenames: false
        args:
          - -c
          - |
            if command -v trivy >/dev/null 2>&1; then
              trivy fs --security-checks vuln,secret,config --severity HIGH,CRITICAL --exit-code 1 . || echo "Trivy scan completed with findings"
            else
              echo "Trivy not found, skipping security scan"
            fi