kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: langflow-dev
nodes:
- role: control-plane
  extraPortMappings:
  # OpenWebUI (HTTP)
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
  # Langflow UI (HTTP)
  - containerPort: 30001
    hostPort: 7860
    protocol: TCP
  # Pipelines API
  - containerPort: 30002
    hostPort: 9099
    protocol: TCP
  # PostgreSQL (for external access)
  - containerPort: 30003
    hostPort: 5432
    protocol: TCP
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
