{{- range $serverName, $server := .Values.mcpServers }}
{{- if $server.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langflow-app.fullname" $ }}-mcp-{{ $serverName }}
  labels:
    {{- include "langflow-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mcp-server
    mcp.server/name: {{ $serverName }}
spec:
  replicas: {{ $server.replicas }}
  selector:
    matchLabels:
      {{- include "langflow-app.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: mcp-server
      mcp.server/name: {{ $serverName }}
  template:
    metadata:
      labels:
        {{- include "langflow-app.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: mcp-server
        mcp.server/name: {{ $serverName }}
    spec:
      containers:
        - name: mcp-{{ $serverName }}
          image: "{{ $server.image.repository }}:{{ $server.image.tag }}"
          imagePullPolicy: {{ $server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $server.service.port }}
              protocol: TCP
          {{- if or $server.env $server.secrets }}
          env:
            {{- if $server.env }}
            {{- toYaml $server.env | nindent 12 }}
            {{- end }}
            {{- if $server.secrets }}
            {{- range $key, $value := $server.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "langflow-app.fullname" $ }}-mcp-{{ $serverName }}-secrets
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            {{- if $server.existingSecret }}
            {{- range $envName := (keys $server.secrets | default list) }}
            - name: {{ $envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $server.existingSecret }}
                  key: {{ $envName }}
            {{- end }}
            {{- end }}
            {{- with $.Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml $server.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow-app.fullname" $ }}-mcp-{{ $serverName }}
  labels:
    {{- include "langflow-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mcp-server
    mcp.server/name: {{ $serverName }}
spec:
  type: {{ $server.service.type }}
  ports:
    - port: {{ $server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "langflow-app.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: mcp-server
    mcp.server/name: {{ $serverName }}
{{- end }}
{{- end }}
