{{- if .Values.openwebui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langflow-app.fullname" . }}-openwebui
  labels:
    {{- include "langflow-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "langflow-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: openwebui
  template:
    metadata:
      labels:
        {{- include "langflow-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: openwebui
    spec:
      containers:
        - name: openwebui
          image: "{{ .Values.openwebui.image.repository }}:{{ .Values.openwebui.image.tag }}"
          imagePullPolicy: {{ .Values.openwebui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OPENAI_API_BASE_URL
              value: "http://{{ include "langflow-app.fullname" . }}-mcp:{{ .Values.mcp.service.port }}/v1"
            - name: OPENAI_API_KEY
              value: "mcp-integration-key"
            - name: ENABLE_SIGNUP
              value: "true"
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.openwebui.resources | nindent 12 }}
          volumeMounts:
            - name: openwebui-data
              mountPath: /app/backend/data
      volumes:
        - name: openwebui-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow-app.fullname" . }}-openwebui
  labels:
    {{- include "langflow-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui
spec:
  type: {{ .Values.openwebui.service.type }}
  ports:
    - port: {{ .Values.openwebui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "langflow-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: openwebui
{{- end }}