{{/*
Create secrets for sensitive data like API keys, tokens, and passwords.
This template creates Kubernetes Secret objects that can be safely referenced by deployments.
*/}}

{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow-app.fullname" . }}-secrets
  labels:
    {{- include "langflow-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.langflow }}
  {{- if .Values.secrets.langflow.superuserPassword }}
  langflow-superuser-password: {{ .Values.secrets.langflow.superuserPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.secrets.postgresql }}
  {{- if .Values.secrets.postgresql.password }}
  postgresql-password: {{ .Values.secrets.postgresql.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.postgresql.postgresPassword }}
  postgresql-postgres-password: {{ .Values.secrets.postgresql.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}

{{/*
Create individual secrets for each MCP server that has sensitive data
*/}}
{{- range $serverName, $server := .Values.mcpServers }}
{{- if and $server.enabled $server.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow-app.fullname" $ }}-mcp-{{ $serverName }}-secrets
  labels:
    {{- include "langflow-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mcp-server
    mcp.server/name: {{ $serverName }}
type: Opaque
data:
  {{- range $key, $value := $server.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
