# Default values for langflow-app (English only; minimal config for K8s deployment).
replicaCount: 1  # Scale app pods

image:
  repository: langflowai/langflow
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 7860

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: langflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# PostgreSQL configuration
postgresql:
  enabled: true  # Deploy dedicated PostgreSQL
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  auth:
    database: langflow_db  # Dedicated per tool
    username: langflow_user
    password: changeme  # Use secrets in production
  persistence:
    enabled: true
    size: 8Gi  # Scalable storage
    storageClass: ""
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# MCP Servers configuration - Easy to add multiple servers for different apps
mcpServers:
  # Example MCP server for GitHub integration
  github-mcp:
    enabled: true
    replicas: 1
    image:
      repository: modelcontextprotocol/server-github
      tag: "latest"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9099
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    env:
      - name: GITHUB_PERSONAL_ACCESS_TOKEN
        value: ""  # Set your token here
  
  # Example MCP server for filesystem operations
  filesystem-mcp:
    enabled: false
    replicas: 1
    image:
      repository: modelcontextprotocol/server-filesystem
      tag: "latest"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9100
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 250m
    env: []

  # Example MCP server for web scraping
  brave-search-mcp:
    enabled: false
    replicas: 1
    image:
      repository: modelcontextprotocol/server-brave-search
      tag: "latest"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9101
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    env:
      - name: BRAVE_API_KEY
        value: ""  # Set your API key here

# Open WebUI configuration (optional)
openwebui:
  enabled: false
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "main"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# For dynamic configs in Azure/K8s with Helm
extraEnv: []

# Configuration
config:
  langflowConfigDir: "/app/langflow"
  langflowAutoLogin: "false"
  langflowSuperuser: "admin"
  langflowSuperuserPassword: "admin123"