# Default values for langflow-app (English only; minimal config for K8s deployment).
replicaCount: 1  # Scale app pods

image:
  repository: langflowai/langflow
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 7860

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: langflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# PostgreSQL configuration
postgresql:
  enabled: true  # Deploy dedicated PostgreSQL
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  auth:
    database: langflow_db  # Dedicated per tool
    username: langflow_user
    password: changeme  # Use secrets in production
  persistence:
    enabled: true
    size: 8Gi  # Scalable storage
    storageClass: ""
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# MCP Server configuration
mcp:
  enabled: true
  replicas: 1  # Easy to increase for adding more MCP servers
  image:
    repository: ghcr.io/open-webui/pipelines
    tag: "main"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9099
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# Open WebUI configuration (optional)
openwebui:
  enabled: false
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "main"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# For dynamic configs in Azure/K8s with Helm
extraEnv: []

# Configuration
config:
  langflowConfigDir: "/app/langflow"
  langflowAutoLogin: "false"
  langflowSuperuser: "admin"
  langflowSuperuserPassword: "admin123"